name: parallax
services:
  parallax:
    image: roylvzn/parallax:latest
    container_name: parallax
    build:
      context: .
      dockerfile: Dockerfile

    network_mode: host
    ipc: host

    stdin_open: true
    tty: true

    privileged: true

    volumes:
      - .:/workspace/Parallax
      - /home/rr-vzn/rplidar_sdk:/root/rplidar_sdk:ro
      - /tmp/argus_socket:/tmp/argus_socket

    working_dir: /workspace/Parallax

    restart: unless-stopped