#pragma once

#include <parallax/isp/frame_types.hpp>
#include <cuda_runtime.h>

namespace parallax::isp {

    /**
    * Convert a combined side-by-side BA10 Bayer image into separate
    * full-resolution RGB8 and grayscale left/right images.
    *
    * Both outputs are generated by the same CUDA kernel.
    * This function only enqueues GPU work.
    */

    bool demosaicAndSplit(const GpuBayerFrame& input, 
                        StereoRgbFrame& rgb_output, 
                        StereoGrayFrame& gray_output, 
                        cudaStream_t stream);

}