<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>px_calibration</name>
  <version>0.0.0</version>
  <description>consume left/right frames + camera info, detect the calibration target,
                run OpenCV/CUDA-X stereo calibration, produce K1/D1/K2/D2/R/T/E/F, 
                then stereo rectify to produce R1/R2/P1/P2/Q, 
                and write the resulting calibration YAMLs.</description>
  <maintainer email="noemail@outlook.com">Louis M</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
