<?xml version="1.0"?>
<package format="3">
  <name>camera</name>
  <version>3.1.0</version>
  <description>AR0234 stereo ingress and calibrated ROS stereo products.</description>
  <maintainer email="noreply@noreply.local">LouisM</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
