stereo_camera:
  ros__parameters:
    perception:
      nanoowl_engine: /models/nanoowl/owl_image_encoder_patch32_fp16.engine
      sam_encoder_engine: /models/efficientvit-sam/l0_encoder_fp16.engine
      sam_decoder_engine: /models/efficientvit-sam/l0_decoder_fp16.engine
